-- MySQL Script generated by MySQL Workbench
-- 10/17/18 16:33:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -------------------------------------------------------
-- Crée la base de données et l'utilise
-- -------------------------------------------------------
CREATE DATABASE oshop_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE oshop_db;

-- -------------------------------------------------------
-- Table: category
-- -------------------------------------------------------
CREATE TABLE category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO category (name) VALUES 
('Papeterie'),
('Stylos'),
('Calculatrices'),
('Cartables'),
('Agendas');

-- -------------------------------------------------------
-- Table: brand
-- -------------------------------------------------------
CREATE TABLE brand (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO brand (name) VALUES 
('BIC'),
('Parker'),
('Maped'),
('Faber-Castell'),
('Clairefontaine');

-- -------------------------------------------------------
-- Table: type
-- -------------------------------------------------------
CREATE TABLE type (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO type (name) VALUES 
('Stylo-bille'),
('Stylo-plume'),
('Feutre'),
('Crayon'),
('Feuille / Cahier');

-- -------------------------------------------------------
-- Table: product
-- -------------------------------------------------------
CREATE TABLE product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10,2),
    brand_id INT,
    category_id INT,
    type_id INT,
    FOREIGN KEY (brand_id) REFERENCES brand(id),
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (type_id) REFERENCES type(id)
);

-- Quelques produits d'exemple
INSERT INTO product (name, description, price, brand_id, category_id, type_id)
VALUES
('Stylo-bille BIC Cristal', 'Stylo-bille emblématique pour l\'écriture quotidienne', 1.50, 1, 2, 1),
('Crayon Faber-Castell HB', 'Crayon à papier haute qualité pour l\'école et le bureau', 0.80, 4, 1, 4),
('Cartable Parker Deluxe', 'Cartable élégant pour transporter vos fournitures', 35.00, 2, 4, NULL),
('Feutre Maped Color\'Peps', 'Feutre de coloriage résistant pour enfants et adultes', 3.50, 3, 1, 3),
('Cahier Clairefontaine 24x32', 'Cahier grand format, papier de haute qualité', 2.50, 5, 1, 5),
('Calculatrice scientifique Casio', 'Fonctions avancées pour le lycée et l\'université', 19.99, NULL, 3, NULL);

-- Les FOREIGN KEY sur brand_id, category_id, type_id peuvent être NULL si le produit n'appartient pas forcément à une marque / type.
